### ISSUE TITLE
Lab errors

### ISSUE THREAD

**Issue by AlekseiMaslakov** [antufievsemen/Labs#2]
Здравствуйте
По лабам:
**Lab1.a**: данный фрагмент кода никак не защищает ваш код от ошибки ввода
![image](https://user-images.githubusercontent.com/14160551/68472571-d5181600-0231-11ea-8456-b35b2386994e.png)
Исключение в данном случае не кидается и нигде не обрабатывается.
**Lab1.b**: то же самое, в данном случае исключение будет брошено, но нигде не обработано и программа завершится с ошибкой.
В принципе писать throws в методе main нельзя ни при каких условиях, потому что все брошенные таким образом исключения не будут нигде обработаны
![image](https://user-images.githubusercontent.com/14160551/68472779-49eb5000-0232-11ea-898e-6cfb4a109107.png)
**Lab1.c**: см. предыдущие 2

**Lab2.D&E**: абсолютные пути будут работать только на вашей машине, при написании кода нужно пользоваться относительными

**Lab4**: максимально недружественный интерфейс взаимодействия для пользователя - нет описание какие команды можно вводить, ни слова о формате команд и их последовательности

**Lab5**: см. Lab2.D&E

**Comment by antufievsemen** [comment]
Исправил все выше перечисленное
